### ISSUE TITLE
Payment with a 3-D verification card

### ISSUE THREAD

**Issue by MuhammedRefaat** [payfort/start-android-sdk#5]
There is a Bug in Payfort Android Start sdk which is appears when pay using a card with a 3-D verification.

**problem:**
- typing the password or the OTP of the card when paying with a card with 3-D verification.

**How to reproduce:**
- call any Payfort api related to payment step with a new card, and this card must be protected by a 3-D verification techniques(SMS, Password, ...etc).
- a new page will be opened for the card verification process, this page is opened through a webview inflated by the method `showVerificationDialog()` at the class Start.java at payfort sdk.
- in the new page, try to write the password at the corresponding field, the KB will not open at all and hence you will not be able to provide the required verification.

**How to Solve:**
There are two ways:

1. request the focus for the webview at `showVerificationDialog()` method.

2. create a dummy & hidden EditText attached at the same layout for the webView to capture the focus for the layout.

-----------------------------------------------

All the details about the problem and how to solve it can be found at my StackOverflow question & answer at [that link](https://stackoverflow.com/questions/46273173/payfort-with-3-d-secure-credit-cards).

**Comment by alovak** [comment]
hi @MuhammedRefaat! Thanks for reporting this.

Let us look at it and if we can fix it on our side...

**Comment by danikula** [comment]
Hi @MuhammedRefaat! Thanks for great explanation and your help. Fix is included in version [0.3](https://bintray.com/pavel-gabriel/payfort/start/0.3).

**Comment by MuhammedRefaat** [comment]
@alovak @danikula Thank you so much guys for caring and for your quick response.
